### ISSUE TITLE
An error occurred while sending the request

### ISSUE THREAD

**Issue by spisebanan** [Sbanken/api-examples#15] opened 2018-04-25 10:35 UTC
I get an error when running the example code from: 
https://github.com/Sbanken/api-examples/tree/master/DotNetCoreSampleApplication

I have checked the clientId, secret and customerId again and again, and have verified that there are no hidden characters inside any of these strings. 
I have regenerated new secret and tried again. 

One other person has tried running the same code with his own clientId and secret, and for him the code runs without any problem. 

I do have a letter ø inside my name. I wonder if that might be the reason. Could it be that the API is generated based on the name, and that the norwegian letters are not valid?
Or are there any other solutions/ suggestions?

I use .Net Core 2.0 and the Sbanken.DotNet 0.2.0 (NuGet package; https://www.nuget.org/packages/Sbanken.DotNet/0.2.0/ )

This is the error I get in the RunAsync().Wait(); 

System.AggregateException
  HResult=0x80131500
  Message=One or more errors occurred. (Error connecting to https://apisbanken.no/identityserver/.well-known/openid-configuration: An error occurred while sending the request.)
  Source=System.Private.CoreLib
  StackTrace:
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at SampleApplication.Program.Main(String[] args) in Program.cs:line 17

Inner Exception 1:
Exception: Error connecting to https://apisbanken.no/identityserver/.well-known/openid-configuration: An error occurred while sending the request.

**Comment by anderaus** [comment] 2018-04-25 15:30
It should be `api.sbanken.no`, not `apisbanken.no`. Also, if you're running the sample code you referred to, you're not really using the `Sbanken.DotNet` package as intended.

For an example on how to use `Sbanken.DotNet`, please see [this readme](https://github.com/anderaus/Sbanken.DotNet/blob/master/README.md) or the included sample application [here](https://github.com/anderaus/Sbanken.DotNet/tree/master/sample/Sbanken.ConsoleApp).

**Comment by spisebanan** [comment] 2018-04-25 22:43
! Oh, my mistake. Thanks again, Anderaus!

**Comment by sbankenOB** [comment] 2018-05-07 08:39
Closing this issue as it seems to be resolved.

**Closed by sbankenOB** 2018-05-07 08:39 UTC
